// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  /*
   * The introduction and homepage provide the curated semantic routes.
   * The sidebar remains a complete filesystem-derived archive so historical
   * material is not hidden or duplicated in a brittle hand-maintained list.
   * Ordering within sections can be refined through document front matter and
   * category metadata as the archive is progressively curated.
   */
  researchSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
